# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_date', models.DateTimeField()),
                ('bid_price', models.IntegerField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=40)),
                ('c_hp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=5)),
                ('condition', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sel_Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=40)),
                ('s_hp', models.CharField(max_length=40)),
                ('register_date', models.DateTimeField()),
                ('init_price', models.IntegerField()),
                ('imm_price', models.IntegerField()),
                ('closing_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sel_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarket.Sel_Reg'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='bidding',
            field=models.ManyToManyField(through='bookmarket.Bid', to='bookmarket.Product'),
        ),
        migrations.AddField(
            model_name='bid',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarket.Candidate'),
        ),
        migrations.AddField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarket.Product'),
        ),
    ]
