# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 16:37
from __future__ import unicode_literals

import bookmarket.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid_Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_date', models.DateTimeField()),
                ('bid_price', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('ME', 'Major_e'), ('MN', 'Major_ne'), ('LI', 'Liberal'), ('ET', 'Etc')], default='ET', max_length=40)),
                ('author', models.CharField(max_length=40, null=True)),
                ('subject', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=5)),
                ('condition', models.CharField(max_length=5)),
                ('register_date', models.DateTimeField()),
                ('init_price', models.IntegerField()),
                ('imm_price', models.IntegerField()),
                ('current_price', models.IntegerField(default=0)),
                ('closing_date', models.DateTimeField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=bookmarket.models.user_directory_path)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bid_candidate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarket.Product_Register'),
        ),
    ]
