# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_register',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
    ]
