# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid_candidate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 2, 56, 7, 923243)),
        ),
        migrations.AlterField(
            model_name='product_register',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 2, 56, 7, 920857)),
        ),
    ]
