# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0002_auto_20170608_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_candidate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 4, 4, 52, 74234)),
        ),
        migrations.AlterField(
            model_name='product_register',
            name='condition',
            field=models.CharField(default='selling', max_length=10),
        ),
        migrations.AlterField(
            model_name='product_register',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 4, 4, 52, 72191)),
        ),
    ]
