# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0002_auto_20170531_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=5)),
                ('condition', models.CharField(max_length=5)),
                ('register_date', models.DateTimeField()),
                ('init_price', models.IntegerField()),
                ('imm_price', models.IntegerField()),
                ('closing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hp', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='sel_reg',
        ),
        migrations.AlterField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarket.Product_Register'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bidding',
            field=models.ManyToManyField(through='bookmarket.Bid', to='bookmarket.Product_Register'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sel_Reg',
        ),
        migrations.AddField(
            model_name='product_register',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarket.Seller'),
        ),
    ]
