# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-03 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0003_auto_20170531_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_register',
            name='image',
            field=models.ImageField(default=datetime.datetime(2017, 6, 3, 9, 11, 26, 525124, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
