# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0003_auto_20170531_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_register',
            name='category',
            field=models.CharField(choices=[('ME', 'Major_e'), ('MN', 'Major_ne'), ('LI', 'Liberal'), ('ET', 'Etc')], default='ET', max_length=40),
        ),
        migrations.AlterField(
            model_name='seller',
            name='hp',
            field=models.IntegerField(default=0),
        ),
    ]
