# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 06:23
from __future__ import unicode_literals

import bookmarket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0004_product_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_register',
            name='author',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product_register',
            name='image',
            field=models.ImageField(upload_to=bookmarket.models.user_directory_path),
        ),
    ]
