# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0004_auto_20170608_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_register',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 17, 23, 17, 192962)),
        ),
    ]
