# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0005_auto_20170604_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_register',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
