# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0006_auto_20170604_1307'),
        ('bookmarket', '0006_auto_20170604_2206'),
    ]

    operations = [
    ]
