# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0006_auto_20170608_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_register',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 20, 30, 24, 673433)),
        ),
    ]
