# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 14:16
from __future__ import unicode_literals

import bookmarket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_register',
            name='image',
            field=models.ImageField(default=0, upload_to=bookmarket.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='seller',
            name='hp',
            field=models.CharField(max_length=40),
        ),
    ]
