# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0008_auto_20170608_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_register',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 20, 34, 13, 2984)),
        ),
    ]
