# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 16:12
from __future__ import unicode_literals

import bookmarket.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0008_auto_20170604_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_register',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=bookmarket.models.user_directory_path),
        ),
    ]
