# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import groupbuying.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField()),
                ('comment', models.CharField(max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party_Open',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=40)),
                ('open_date', models.DateTimeField()),
                ('num_person', models.IntegerField()),
                ('now_person', models.IntegerField(default=1)),
                ('closing_date', models.DateTimeField()),
                ('image', models.ImageField(default=0, upload_to=groupbuying.models.user_directory_path)),
                ('condition', models.CharField(choices=[('RE', 'Recruiting'), ('SF', 'Sfail'), ('SS', 'Ssucc'), ('SC', 'Scanc')], default='RE', max_length=10)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='apply_applicant',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupbuying.Party_Open'),
        ),
    ]
