# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import groupbuying.models


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_open',
            name='image',
            field=models.ImageField(default=0, upload_to=groupbuying.models.user_directory_path),
        ),
    ]
