# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuying', '0002_party_open_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_open',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
