# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuying', '0003_auto_20170604_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_open',
            name='condition',
            field=models.CharField(choices=[('RE', 'Recruiting'), ('SF', 'Sfail'), ('SS', 'Ssucc'), ('SC', 'Scanc')], default='RE', max_length=5),
        ),
        migrations.AlterField(
            model_name='party_open',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
