# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuying', '0004_auto_20170605_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party_open',
            name='condition',
            field=models.CharField(choices=[('RE', 'Recruiting'), ('SF', 'Sfail'), ('SS', 'Ssucc'), ('SC', 'Scanc')], default='RE', max_length=10),
        ),
    ]
