# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_date', models.DateTimeField()),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seek_Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=40)),
                ('depart_date', models.DateField()),
                ('depart_time', models.TimeField()),
                ('num_person', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hp', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='attending',
            field=models.ManyToManyField(through='taxipool.Attend', to='taxipool.Seek_Taxi'),
        ),
        migrations.AddField(
            model_name='attend',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxipool.Passenger'),
        ),
        migrations.AddField(
            model_name='attend',
            name='seek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxipool.Seek_Taxi'),
        ),
    ]
