# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend_Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_date', models.DateTimeField()),
                ('comment', models.CharField(max_length=100)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seek_Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=40)),
                ('depart_date', models.DateField()),
                ('depart_time', models.TimeField()),
                ('num_person', models.IntegerField(max_length=4)),
                ('now_person', models.IntegerField(default=1)),
                ('content', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('SE1', 'Seeking'), ('SF1', 'Sefail'), ('SS1', 'Sesucc'), ('SC1', 'Secanc')], default='SE1', max_length=10)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attend_passenger',
            name='taxi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxipool.Seek_Taxi'),
        ),
    ]
