# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxipool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seek_taxi',
            name='title',
        ),
    ]
