# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxipool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seek_taxi',
            name='condition',
            field=models.CharField(choices=[('SE', 'Seeking'), ('SF', 'Sfail'), ('SS', 'Ssucc'), ('SC', 'Scanc')], default='SE', max_length=5),
        ),
    ]
