# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxipool', '0002_seek_taxi_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seek_taxi',
            name='condition',
            field=models.CharField(choices=[('SE1', 'Seeking'), ('SF1', 'Sefail'), ('SS1', 'Sesucc'), ('SC1', 'Secanc')], default='SE1', max_length=10),
        ),
    ]
